language: python
python:
  - "3.5"
  - "3.6"
  - "2.7"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda 
  - export PATH=/home/travis/miniconda/bin:$PATH

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib pip pymongo flake8
  - pip install .

script:
  - flake8 taco_salat
  - python setup.py test
